conservative:
  - name: "Fox News (US RSS)"
    type: "media"
    urls:
      - "https://moxie.foxnews.com/google-publisher/us.xml"
  - name: "National Review (RSS)"
    type: "media"
    urls:
      - "https://www.nationalreview.com/feed"

liberal:
  - name: "The Intercept (RSS)"
    type: "media"
    urls:
      - "https://theintercept.com/feed"
  - name: "Jacobin (RSS)"
    type: "media"
    urls:
      - "https://jacobin.com/feed"
